# The full repository name
repo: go-gitea/gitea

# Service type (gitea or github)
service: github

# Base URL for Gitea instance if using gitea service type (optional)
# Default: https://gitea.com
base-url:

# Changelog groups and which labeled PRs to add to each group
groups:
  -
    name: BREAKING
    labels:
      - kind/breaking
  -
    name: SECURITY
    labels:
      - kind/security
  -
    name: FEATURES
    labels:
      - kind/feature
  -
    name: API
    labels:
      - kind/api
  -
    name: ENHANCEMENTS
    labels:
      - kind/enhancement
      - kind/refactor
      - kind/ui
  -
    name: BUGFIXES
    labels:
      - kind/bug
  -
    name: TESTING
    labels:
      - kind/testing
  -
    name: TRANSLATION
    labels:
      - kind/translation
  -
    name: BUILD
    labels:
      - kind/build
      - kind/lint
  -
    name: DOCS
    labels:
      - kind/docs
  -
    name: MISC
    default: true

# regex indicating which labels to skip for the changelog
skip-labels: skip-changelog|backport\/.+
